package com.example.meeqapp.ui.onboarding

const val GOAL_SCREEN = "GOAL_SCREEN"
const val CONDITION_SCREEN = "CONDITION_SCREEN"
const val FAMILIARITY_SCREEN = "FAMILIARITY_SCREEN"
const val NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN"
const val CHECKUP_PROMPT_SCREEN = "CHECKUP_PROMPT_SCREEN"
const val WELCOME_SCREEN = "WELCOME_SCREEN"
const val ANXIETY_CHECK_SCREEN = "ANXIETY_CHECK_SCREEN"
const val PREDICTION_PROMPT_SCREEN = "PREDICTION_PROMPT_SCREEN"