package com.sprytm.meeqapp.ui

const val MAIN_SCREEN = "MAIN_SCREEN"
const val EXPLANATION_SCREEN = "EXPLANATION_SCREEN"
const val SETTING_SCREEN = "SETTING_SCREEN"
//const val PAYMENT_SCREEN = "PAYMENT_SCREEN"
const val CBT_VIEW_SCREEN = "CBT_VIEW_SCREEN"
const val LOCK_SCREEN = "LOCK_SCREEN"
const val CHECKUP_SCREEN = "CHECKUP_SCREEN"
const val SUPPORT_SCREEN = "SUPPORT_SCREEN"
const val MARKDOWN_ARTICLE_SCREEN = "MARKDOWN_ARTICLE_SCREEN"

const val CBT_ON_BOARDING_SCREEN = "CBT_ON_BOARDING_SCREEN";
const val CBT_FORM_SCREEN = "CBTFormScreen"
const val CBT_LIST_SCREEN = "CBTListScreen"

const val THOUGHT_SCREEN = "THOUGHT_SCREEN"
const val DISTORTION_SCREEN = "DISTORTION_SCREEN"
const val CHALLENGE_SCREEN = "CHALLENGE_SCREEN"
const val ALTERNATIVE_SCREEN = "ALTERNATIVE_SCREEN"
const val FINISHED_SCREEN = "FINISHED_SCREEN"
const val FEELING_SCREEN = "FEELING_SCREEN"
const val AUTOMATIC_THOUGHT_SCREEN = "AUTOMATIC_THOUGHT_SCREEN"
const val AUTOMATIC_THOUGHT_ONBOARDING_SCREEN = "AUTOMATIC_THOUGHT_ONBOARDING_SCREEN"

// Regular thought Follow-up screens
const val FOLLOW_UP_REQUEST_SCREEN = "FOLLOW_UP_REQUEST_SCREEN"
const val FOLLOW_UP_FEELING_SCREEN = "FOLLOW_UP_FEELING_SCREEN"
const val FOLLOW_UP_FEELING_REVIEW_SCREEN = "FOLLOW_UP_FEELING_REVIEW_SCREEN"
const val FOLLOW_UP_NOTE_SCREEN = "FOLLOW_UP_NOTE_SCREEN"

// Feedback
const val FEEDBACK_SCREEN = "FEEDBACK_SCREEN"
const val FEEDBACK_LEAVE_REVIEW = "FEEDBACK_LEAVE_REVIEW"
const val SURVEY_SCREEN = "SURVEY_SCREEN"

// Checkup
const val CHECKUP_SUMMARY_SCREEN = "CHECKUP_SUMMARY_SCREEN"

const val SCREENING_ROUTE = "SCREENING_ROUTE"



